#!/usr/bin/python3
import sys
import os
j = os.path.join
sys.path.append(j(os.getenv("HOME"), "pwn"))
from config import path, bit_32

x = "" if bit_32 else "64"
os.system(f"cd ~/pwn/.server && ./linux_server{x}")
